### PR TITLE
Router Reborn

### PR DESCRIPTION
**Pull request by BBoldt**
Before:

After:

Before: 

After:

### CODE REVIEW

**Comment by WittyYeti** [comment]
They not terrible, it just needs a little more color variation. Go check out the other pull requests for some advice :)

**Comment by asiekierka** [comment]
YES.

**Comment by CyanideX** [comment]
Hey, @BBoldt. Review some of the feedback left here. :stuck_out_tongue: 

Color variation is important in the Unity textures; the screens shouldn't be shades of a single color. I also think the vent lines are a little too dark. This is just a sample of a more metallic looking router with blended elements and color variation:

router

**Comment by BBoldt** [comment]
Moved to #23

**Pull request closed without merging**
