### PR TITLE
Thermal Expansion 1.7.10 update

### PR DESCRIPTION
**Pull request by VapourDrive**
Removed the redundant assets that were moved over to thermal dynamics or thermal foundation.
Added new textures for the caches, sponges, sachels, upgrades, lock,
igniter, plates
Some minor tweaks
-fixed the tesselator glitch with the strongboxes.
-tweaked the general capacitor looks a tad, slightly more depth now.

Old Upgrades

New Upgrades

The new upgrades are designed to look similar to the old ones, a little less in your face with the background colour, and not taking up the while 16x16 pixels, as it looks really bad when they are in your inventory or slots etc. The background textures are included if just the background needs tweaking or for future upgrades.

Old Caches

New Caches

The cache textures include a unified version for easy hue/contrast/level change over all sides.

Old Plates

New Plates (the fluid render isn't technically part of the plate, its called from the actual fluid asset)

Old Sponges

New Sponges

Old Misc Items

New Misc Items

### CODE REVIEW

**Comment by Drullkus** [comment]
I'm not sure what I think of the arguments... They're a bit too gray :S

**Comment by VapourDrive** [comment]
Most of the things in Thermal X mods got a bit of colour taken out of them so that they fit the style. The actual emblems in the upgrades are still fairly bright and now the background, although still very distinguishable between tiers doesn't distract as much.
They can be changed fairly easily though.

**Comment by VapourDrive** [comment]
Couple assets got away, take no action yet...

**Comment by VapourDrive** [comment]
All machines now have the correct texture's for their faces
Cyanide's:

TE


Machine Frame textures
New:

Old:

The inner coulouring is drawn from the metal storage block textures - tin, electrim, signalum, and enderium.

**Comment by BBoldt** [comment]
I just wanted to chime in here, I think these look fantastic.

The only thing that bothers me a tiny bit is the doubled look of the two upper tier caches. Looks a bit out of place to me.

**Comment by VapourDrive** [comment]
@BBoldt they look fantastic because most of them are CyanideX's :). I do agree that the doubled nature of the reinforced and resonant cache is a tad out of place. I think I might change them and throw a couple extra rivets down the side, they should have some sort of differentiating feature besides just colour imho.
Thanks for the feedback :)

**Comment by VapourDrive** [comment]
This now also includes a small ReadMe fix from kamran mackey.

**Comment by Nentify** [comment]
I kind of miss a bit of the colour from the old machines and items to be perfectly honest. They are nice nonetheless, but just feel a bit dull now.

**Pull request closed without merging**
