### PR TITLE
Retexture for Steve's Factory Manager w/ Steve's Addons

### PR DESCRIPTION
**Pull request by goranalkovic**
I decided to give a try at retexturing SFM ( *again* ), this time with even more Unity in mind.

The _Machine Inventory Manager_ UI is the only one that differs much from Unity. It's more flat and less noisy:

Here are some other blocks:

### Things to note

**-** Currently needs Steve's Addons installed for the _Machine Inventory Manager_ new UI
**-** Some textures aren't present yet (SFM Relay, some Steve's Addons items)

### CODE REVIEW

**Comment by CyanideX** [comment]
Wow.

That UI looks beautiful. :)

**Comment by goranalkovic** [comment]
Thanks :)
Worked on it for 4-5 hours, tried out tons of combos, ended up looking like this. Glad you like it!

**Comment by CyanideX** [comment]
Oh, forgot to ask if this was final and ready to merge.

**Comment by CyanideX** [comment]
Whoops, forgot to merge! Looks good to go. :)

**Comment by goranalkovic** [comment]
I'll do the SFM-only version this weekend (the Steve's Addons mod adds cool things, but it changes the button order in the UI a bit, so the vanilla SFM is a tad different).

**Pull request merged**
