### PR TITLE
Chisel marble

### PR DESCRIPTION
**Pull request by ScottKillen**
Hybrid textures with a good marble pattern.

Before:

After:

### CODE REVIEW

**Comment by Yulife** [comment]
Is it just me or does your Marble look 32x32?

**Comment by ScottKillen** [comment]
@Yulife technically they are 32x, but in reality they are hybrid textures (32x designed to fit into a 16x pack) based on @CyanideX own work and a conversation I had with him.

To me, it doesn't really make sense to retexture marble unless it is done in this way, but if he doesn't like them they will be gone.

**Comment by MechWarrior99** [comment]
To me it looks to 32x32 it does not really look 16x16 to me.

**Comment by CyanideX** [comment]
With hybrid textures, the base texture should be 16x and small, almost unnoticeable details added for depth. In my opinion, I don't think the base marble texture should be 32x.

**Comment by ScottKillen** [comment]
Thanks. I'll see what I can do.

**Comment by Drullkus** [comment]
Personally I don't think you can just take the bevels off the chisel marble textures and then put them on the new blocks :\

Sorry, going through old tickets to see awesome unity content :P

**Comment by ScottKillen** [comment]
I didn't do that. I am not sure how to remove the bevels from a texture. 

I actually spent quite a while generating a new marble texture...

**Comment by Drullkus** [comment]
What do you mean? Just make new bevels? :o

**Comment by Yulife** [comment]
@Drullkus what in the world do you think of a bevel in a 16x16 :p

**Comment by Drullkus** [comment]
Yep

**Comment by ScottKillen** [comment]
I'm very confused. I just pulled up the JSTR marble textures (see below) and they are not even close to my work here...  Are you just trolling me @Drullkus ?

Blue power marble

Chisel marble

**Comment by Drullkus** [comment]
I made neither marble textures. I plan to retexture the marble if you're not going to make unity marble :P

Also. What's JSTR

**Comment by ScottKillen** [comment]
I read your first November 28 comment wrong...and then my confusion cascaded from there. I can be an idiot at times.

I do not currently plan on resubmitting these. Go for it. :grinning:

**Pull request closed without merging**
