### PR TITLE
restore BinnieCore compartment, ExtraBees hive textures

### PR DESCRIPTION
**Pull request by asiekierka**
From 1.7.10.

### CODE REVIEW

**Comment by CyanideX** [comment]
Those aren't Unity compartments though, are they?

**Comment by asiekierka** [comment]
The files are from the 1.7.10 branch, so they're compartments from the mod BinnieCore and I assume they are retextured to match the Unity style already...?

**Comment by CyanideX** [comment]
They _might've_ been residual textures that I forgot to remove. I don't think they were textured.

**Comment by asiekierka** [comment]
To my eye, they seem to be - but only partially. The compartment itself is not retextured, but the metal component of it seems to be retextured to match the Unity metals.

Either way, I'm a terrible texture artist and I'm too scared to touch them.

**Comment by CrankySupertoonArchive** [comment]
@CyanideX actually they were a PR that you declined https://github.com/CyanideX/Unity/pull/2

**Comment by CyanideX** [comment]
Sorry I never got around to this. 😅

**Pull request closed without merging**
