### PR TITLE
Advanced Machines - Add item texture

### PR DESCRIPTION
**Pull request by InsomniaKitten**
## 

sharp_plate_example

**Sharpened Iron Plate -** `assets/advanced_machines/textures/items/sharp_plate.png`

This item didn't exist in 1.7.10 and needed a new texture.
Critical opinions are welcome. Crafting recipe as seen below.

Comparison alongside plates from Unity's IC2 textures.

### CODE REVIEW

**Comment by InsomniaKitten** [comment]
Second revision:

sharp_plate_example_rev_2

**Comment by Yulife** [comment]
Huh, I thought I made a texture for it? Let me see

**Comment by Yulife** [comment]
Apparently it was never commited, weird. What's the difference between "advancedmachines" and "advanced_machines" asset folder btw?

**Comment by InsomniaKitten** [comment]
`advancedmachines` is the one that supports the original 1.7.10 mod.

If you have a texture already then use that, I don't mind scrapping mine/keeping it for my own personal use. ^-^

**Comment by InsomniaKitten** [comment]
I'm glad you like it :D Also yeah I love it, it's one of [Meggle's](http://www.planetminecraft.com/member/meggles/skins/any/?morder=order_popularity) skins, they make some pretty awesome characters. I need to get around to making my own personal skin some day though :P

**Pull request merged**
