### PR TITLE
Add support for Magic/More Bees

### PR DESCRIPTION
**Pull request by Alan19**
Since magic bees got released for 1.12, Magic Bees hive textures should be re-added. These textures should work but I'll double check tomorrow. Suggested by someone in #140.

### CODE REVIEW

**Comment by Alan19** [comment]
They work 😄

**Comment by Alan19** [comment]
I added a commit for more bees because it has a rock hive block that can be copied from extra bees. Should I revert it for now?

**Review by ChloeDawn — CHANGES_REQUESTED** [review]
Beehives 0, 1, and 2 do not fit in with the theme. The colors used for the base and lines mix poorly. Please try to maintain consistency with the existing textures; use a darker shade of the base texture for the lines, not a new color.  Beehives 3, 4, and 5 are far too noisy. Please reference the existing Forestry hive textures on the amount of acceptable noise.

**Comment by ChloeDawn** [comment]
I am aware that the Magic Bees hives are noisy in their own respect. That does not mean they should be in Unity. A custom texture may be applicable, but excessive noise is definitely not the solution.

**Comment by BBoldt** [comment]
When I made these it was just a band aid to make them not so drastically different than the originals. I was very new to texturing at the time and they are mostly recolors of the basic unity hive. 

For the first 3 I just used the colors that magic bees originally used, which look bad together. 
For the other 3 I blended the unity forestry hive with the textures for netherrack, end stone, and stone, because that's where those ones spawn. That's why they look so noisy. They are also very poorly animated.

Honestly they probably all need to be scrapped and redone from scratch. They don't need to look so much like the forestry unity hive either. They are M A G I C A L. Get creative! Unfortunately I don't have the time or motivation to do textures anymore. It's not that difficult though! You can learn to do anything if you practice, and this would be a good way to practice.

**Pull request closed without merging**
