### PR TITLE
Endstone ore textures

### PR DESCRIPTION
**Pull request by Endmateria**
Adds Unity Endstone texture to Ebonarts, Cyclic, BOP, RFtools, Mystical Agriculture, and Extreme Reactors end ores.

### CODE REVIEW

**Comment by Endmateria** [comment]
Pic of updated ores...  https://ibb.co/hTic5v

**Comment by CyanideX** [comment]
Thank you for taking the time to do this but I wish you had changed the ores a bit more instead of only swapping the endstone base texture. 😛

**Comment by Endmateria** [comment]
Yeah, sorry... I've got zero drawing skills, but the mismatched textures in the End were irritating me,  so at the very least these ores don't look out of place in the end, at least for the moment.  I mainly made these quickly for personal use on my server, but feel free to use, alter, or discard these... I don't care.  Just trying to contribute what I can.

**Comment by InsomniaKitten** [comment]
No offense, but I think we'll discard these, and cover these ores as we slowly add support for the entire mods.

**Comment by Endmateria** [comment]
That's cool, they work for me, given that no texture pack for mods is ever going to be complete and/or completed before this game becomes obsolete hahaha...  https://www.youtube.com/watch?v=hHRNSeuvzlM

**Comment by InsomniaKitten** [comment]
If you want a mod to be supported, you should make a request for it in an issue report. Don't just assume we'll never get around to it. Textures don't appear from thin air, adding mod support takes time.

**Comment by Endmateria** [comment]
Sorry, I was just butthurt after going through all that effort to figure out pull requests for nothing, as if the picture of the textures/link to the the zip that I posted in the op wasn't enough for you guys to discern whether you wanted to use them or not.  Just seemed like a big waste of my time.  Regardless, my apologies for being rude.

**Comment by CyanideX** [comment]
@Endmateria, I wouldn't say it was a waste of time. You said you made them for your personal use and the time you spent figuring out PRs is useful to know in the future. 😉 Don't stop texturing because your first PR was turned down; it takes time and a lot of practice. I appreciate the effort and your interest in helping Unity.

**Comment by Endmateria** [comment]
For clarity's sake, I'm not emotionally unstable hahaha.  I was mad about being given the runaround, not the rejection itself (so let's not make a strawman argument out of this).  As I said, I'm not a drawer, nor am I a coder, so the odds of me using pull requests again is pretty much zero.  And yes, even though they're just simple re-skins, I am definitely going to use these textures for personal use, so no loss there. The fact that you guys changed the endstone leads to tons of modded textures being off in the end, which I would consider high priority (if I was a tp maker).  Same would apply if you changed stone or netherrack... and it's the primary reason why people with heavily modded setups don't play with texture packs (because worldgen ends up looking like crap).  I do like your textures/work, but in my experience, tp makers have a horrible sense of priority.  Retexture worldgen ores first, retexture inconsequential things like BOP flowers second.   You know, because this looks awesome....  https://ibb.co/eBy1iF

**Comment by CyanideX** [comment]
I retextured Endstone before any popular mods added ores and other content to the End. For the same reason I **didn't** retexture stone or netherrack: I would have applied the same principle to Endstone had I known it would contain ores. My whole purpose with Unity was to have it fit with vanilla and with modded Minecraft, completed or not so Endstone may end up being removed.

For now you can simply delete the Endstone texture from the RP; this was a simple fix that could've saved you a bit of texturing time.

It's not a "horrible sense of priority", as you so kindly summarized, but a time deficiency; I'm not able to keep up with the changes and new additions to the modded scene so things like this pass me by.

**Comment by Endmateria** [comment]
Yeah, but your endstone looks good, so it was worth the re-texture, though I considered removing it.  Stone, netherrack, and endstone seem to be the bane of texture packs... too many mods to accommodate for.  I wondered why you did endstone and not the other two, so I'm glad you explained.  It's a shame, cuz you could probably do some really nice stone and netherrack textures... unfortunately at the expense of a couple hundred mod conflicts hahaha (probably not worth it).  Regardless, "horrible sense of priority" is a relative concept and begs the question... to whom?  To me, yes.  To you no.  It's entirely subjective, hence my disagreement in regard to priorities.  People use texture packs for aesthetics, so why aesthetics would be low priority is beyond me.  Anyways, if you're gonna remove the endstone texture then I guess that that settles that.  Case closed (as you so clearly emphasized).  Now you go be butthurt for a couple hours over my "constructive criticism" like I was yesterday, and tomorrow we can all be friends again hahaha.  Endmateria <3 CyanideX  : p

**Comment by Endmateria** [comment]
Again you missed the point (or simply evaded it).  Whatever, I accept the apology (that you never made) for making me submit a pointless pull request.  Not that I really needed that kind of validation, but it beats people twisting my argument around, while posting smiley faces and irrelevant/condescending advice.  Soooo.... I hate to be the bearer of bad news here, but you kinda reaped the seed you had sown on that one.  But whatever, case closed... I've met my quota of pointless drama for the day.  Enjoy your pull requests hahaha

**Pull request closed without merging**
