### PR TITLE
Avaritia [In need of a new artist]

### PR DESCRIPTION
**Pull request by ZiaAvenicia**
Since no one else has started on it yet, I figured I might as well be the one to do it. Here's what I have done so far - http://i.imgur.com/Tn3s5PX.gif

Also, if anyone wants to help out with the re-texture project, feel free to say what you're going to re-texture so I know not to do it.

### CODE REVIEW

**Comment by MechWarrior99** [comment]
Looking nice. The two block textures on the far left look like they could use a bit more work. Maybe try less blue?

**Comment by ZiaAvenicia** [comment]
Maybe, but it kind of sticks with what the original color scheme of the dire crafting table, which was primarily blue.

**Comment by CyanideX** [comment]
Keep in mind that with Unity you want to keep main elements from the original design but adjust the texture to fit both recipe components and function. It's alright to change the color from, let's say, blue to red if the main component is redstone. I am personally not familiar with this mod so if the recipe contains blue things, nothing to worry about.

**Comment by ZiaAvenicia** [comment]
If that's the case, then I did it right. Both the Dire Crafting Table and Crystal Matrix use the Crystal Ingot that is in the item frame between them, and that item is light blue from the nether star/diamonds that are needed to craft the ingot.

**Comment by ZiaAvenicia** [comment]
I've pretty much finished up Avaritia enough to where I believe its in a commit-able state, so feel free to merge it whenever or tell me if some of the textures aren't up to par.

**Comment by CyanideX** [comment]
Hey @ZiaAvenicia, would you be able to post a screenshot with Unity installed and all of the blocks/items visible ? :smiley: It would make it easier for me to see what you've done.

**Comment by ZiaAvenicia** [comment]
I actually have a few textures to fix, so it'll be a little longer before I can do that. Sorry for the inconvenience.

**Comment by ZiaAvenicia** [comment]
The patch is ready to be merged. Here's every single texture I re-textured - http://gfycat.com/SoupyUnfortunateFishingcat

**Comment by BBoldt** [comment]
@CyanideX told me not to merge, so I'm assuming he wants to give a bit of feedback but hasn't had a chance yet.

As for me, I like it a lot! Looks like you did a good job meshing the avaritia shaders with the textures. 

Some criticisms:
* Animation on the rainbowy blocks is a bit too fast in my opinion, but I don't know if your gfy is sped up at all.
* The super fancy blood magic orb looks too much like the weak blood orb, you may want to add some sparkles to it to give it that "holy shit this orb is OP as fuck" look. Maybe try to recreate the little skull face in the original texture.

I'm going to make a new tag "Needs Feedback" for when a potenital merge is still in review.

**Comment by ZiaAvenicia** [comment]
Okay, thanks for the feedback! I'll look into your suggestions, and I'll be waiting for Cyanide's feedback as well. I'm glad you're liking it so far!  ^_^

**Comment by CyanideX** [comment]
I have issues with the first two blocks. I understand they match the recipe color but visually they aren't Unity and don't make sense to me. Also, some of the items could be redesigned; that star thing and the tool handles (I'm not a fan of the light outlines). The storage block and tool heads should be less white flashy and more of a levels flashy... if that makes sense. And those wings need to be changed. Other than that, I like it. I LOVE blocks 3, 4, and 5! Very well done. :smiley:

**Comment by ZiaAvenicia** [comment]
Okay, I'll look into it. I'm not too sure what you mean by levels flashy. What I'm thinking is that you mean color intensity, but I'll let you say what it means before I work on them. As for the tool handles, I forgot to change the handles to a darker gray after I changed the neutronium ingot/nugget/pile and block, so that shouldn't be that hard of a change.

**Comment by Yulife** [comment]
Girl, those wings are on fleek :information_desk_person:

**Comment by Yulife** [comment]
Is this done?

**Comment by ZiaAvenicia** [comment]
It's not done yet, I still need to revise quite a few textures. I edited the title so that it will hopefully be a little less confusing.

**Comment by BBoldt** [comment]
It's no rush, Yulife is just in a "releasing stuff" mood today for some reason.

Avaritia isn't even really in a fully playable state right now so there is absolutely no reason to rush the textures. Take your time.

**Comment by Yulife** [comment]
Releasing stuff :smiling_imp:

**Comment by TTFTCUTS** [comment]
The machine textures are nice, but where'd the noise go from the neutronium, and where'd the entire crystal matrix pattern go on the crystal matrix stuff? They look totally different!

**Comment by ZiaAvenicia** [comment]
I wasn't too sure where I was going with the Crystal Matrix, and the noise texture doesn't show up on item frames for some reason. It's still there.

**Comment by TTFTCUTS** [comment]
Well, I meant the noise in the borders of the ingot itself - it's not solid white on the original. The halo effect wouldn't render on the item frame because I would have to make it face the view for 3d representations.

**Comment by ZiaAvenicia** [comment]
I never actually noticed the noise texture on the border. I saw that there was an animated texture for the ingot, but I never really payed that much attention for what it was. I guess I should probably add the noise back when I can.

**Comment by TTFTCUTS** [comment]
Oh! That was the other thing, now I finally figured out what was wrong - the neutronium has inverted shading. That's why the shadow is lighter in the original icon. The same extends to all the ticon tool parts, where it can be seen more clearly: https://www.dropbox.com/s/oq3e6bmfexl2po9/ticon03.png?dl=0

Additionally the border is based on that specific shade of pale blue rather than white, which I carried forward to the tools. SpitefulFox made the initial ingot texture and I just went from that.

**Comment by ZiaAvenicia** [comment]
Okay, I'll look into fixing the neutronium textures when I can, thanks for the input! ^_^

**Comment by ZiaAvenicia** [comment]
Since I have kind of stopped working on this patch, if someone wants me to, I can zip up what I have and post it here for someone else to finish/edit, if that's okay. Sorry for the lack of progress.

**Comment by Yulife** [comment]
Go ahead and post all the current textures you have. Let us know which ones we still need to do though :)

**Comment by ZiaAvenicia** [comment]
Actually, you should be able to grab what I have of it on my fork of Unity. https://github.com/ZiaAvenicia/Unity

**Comment by ZiaAvenicia** [comment]
I'm just going to close this because I'm probably not going to finish the textures.

**Comment by CyanideX** [comment]
I wouldn't have closed it. Maybe someone else might want to pick it up. :(

**Pull request closed without merging**
