### PR TITLE
Unity style hive blocks for extra bees, magic bees

### PR DESCRIPTION
**Pull request by BBoldt**
Not perfect, but it's what I've been using in my pack as it's better than only the Forestry hives having Unity textures.

I am by no means a texture artist, but I'm decent at using GIMP. If you have any ideas for things I could do to improve them, feel free to let me know and I'll do my best.

Extra Bees Hives:

Magic Bees Hives:

Gfy because there is a little bit of *not great looking* animation on some of them(sorry, f.lux was on so it's tinted weird):
http://gfycat.com/DeficientGleefulGrunion

The originals for comparison:

### CODE REVIEW

**Comment by CyanideX** [comment]
I think this is a great start to the hives! The animation may need a little tweaking but overall looks pretty good. My one suggestion for the magic hives is to blend the colors a bit more. At the moment it looks a nit noisy and I can't quite place where the lines are sitting (I do very much like the look of the end hive though!)

The other change I would make it to the main hives. Unless I'm mistaken, it looks as though you've colorized them. Instead of altering the overall color, try using a pallet of similar colors to add some highlight and midtones. Here is an example:

pallette

If you want to have another go at the textures, I would be more than happy to offer you my opinion on them and hopefully pull them into Unity. :)

**Comment by BBoldt** [comment]
Yeah I'll take another shot at them. Textures are pretty fun to do.

Just curious, what program do you use to do textures?

**Comment by CyanideX** [comment]
I use Photoshop CC.

**Comment by BBoldt** [comment]
One of these days I'll finish these.

**Comment by BBoldt** [comment]
Closing this because this PR is all fucked up.

I can not github.

I'll reopen it after I take a crack at them again.

**Pull request closed without merging**
