### PR TITLE
Big Reactors

### PR DESCRIPTION
**Pull request by MechWarrior99**
Big Reactors Textures!

### CODE REVIEW

**Comment by Yulife** [comment]
:+1:

**Comment by BBoldt** [comment]
Posting some pics for you

Before:

After: 


Before:

After:


Before:

After:

**Comment by BBoldt** [comment]
Now time for criticisms!

Ore and storage blocks: I think they are too flat and singularly colored. Yellorium is yellow-green, not 'piss in block form' yellow. I think bluetonium needs a bit more green in it as well. Same goes for the others, the Ludicrite could do with a bit more pink in the texture.

Gonna link you to this thing that CyanideX linked me about beehives:


Also, do something more interesting for graphite, people like to use that as a decorative block, so try to keep that 'stacked' pattern it has, but in more of a Unity style.


Your connected textures on the reactor are too blocky. I can see every single block seam. No bueno.



Another thing very jarring is the transition from singular blocks to multiblock, like, yours is more jarring than the transition of the original textures.
 
 

Originals for comparison, notice how subtle the difference is in the reactor. Turbine in the original is too jarring though, yours is better.



I would add a bit more color to the ingots and dusts, check out how VapourDrive did the dusts and ingots for the enderium in Thermal Foundation. That piss ingot and piss dust needs to go. :P

Finally, you didn't texture everything. You're missing textures for the diagnostic tool, the creative mode stuff, and the reactor glass. Just because those things aren't used as much doesn't mean you shouldn't retexture them.

Sorry if I'm a harsh critic, your textures do look very promising, they just need some more work in my opinion.

**Comment by BBoldt** [comment]
Oh, you should add rivets to the reactor casing block.

**Comment by WittyYeti** [comment]
It's not super bad, it's actually pretty good. I will offer you the same advice that @BBoldt did, try and fix those few issues and I'm sure @CyanideX would be happy :)

**Comment by CyanideX** [comment]
This needs to be finished BBoldt! :wink:

**Comment by BBoldt** [comment]
@CyanideX 

Am I @MechWarrior99's handler now? :P

**Comment by CyanideX** [comment]
Precisely why I used the winking emoticon. :stuck_out_tongue:

It's up to you to make sure this get's finished.

**Comment by BBoldt** [comment]
*prepares whip*

**Comment by MechWarrior99** [comment]
Ops, i am in trouble now.

**Pull request closed without merging**
