### PR TITLE
Dev Branch

### PR DESCRIPTION
**Pull request by Yulife**

### CODE REVIEW

**Comment by MechWarrior99** [comment]
Coarse Dirt (need to update it to the new dirt texture) Jungle Doors, Spruce Doors, Prismarine Bricks, Prismarine Rough

**Comment by Yulife** [comment]
Uhhh which new dirt texture? I did coarse dirt I think

**Comment by Yulife** [comment]
Unless there's something else you want me to do for vanilla (in particular 1.8/1.9) @CyanideX please tell me and if not, you can merge this :)

**Comment by Yulife** [comment]
**Minecraft 1.8/1.9:**
unity
**Chisel & Botania:**
unity_chisel_botania

**Comment by BBoldt** [comment]
your granite looks like refried beans

**Comment by ZiaAvenicia** [comment]
I'm not sure if that's supposed to be  a compliment, random comment or something else. .-.

**Comment by Yulife** [comment]
:facepunch: :man: 
I hope you like it @ZiaAvenicia though :P

**Comment by ZiaAvenicia** [comment]
It looks nice to me, but I'll let the other collaborators decide as to whether it's good or not.

**Comment by CyanideX** [comment]
Looks like beans.

**Comment by BBoldt** [comment]
I KNEW IT

**Pull request merged**
