### PR TITLE
Redstone

### PR DESCRIPTION
**Pull request by Mattabase**
Makes Redstone Awesome. 

And those were the wrong screenshots, that was my bad as well.

javaw_2017-07-14_00-18-56

javaw_2017-07-14_00-55-19

### CODE REVIEW

**Comment by Mattabase** [comment]
I have no idea how I managed to add @SnowShock35 to this PR. I am dumb...

**Comment by CyanideX** [comment]
WTF... why is @SnowShock35's commit in there? 😛

**Comment by Mattabase** [comment]
I have no idea how I managed that, or how to fix it lol.

**Comment by CyanideX** [comment]
Awesome screenshots, @Mattabase!

**Comment by ChloeDawn** [comment]
My fault, fixed now; I switched it to embeds to replace the external links when I added the in review label; set the embed URLs to Git's data caches. It's using the image URLs from Twitter now

**Comment by Mattabase** [comment]
Yeah, I also uploaded the wrong screenshots, that has now been fixed.

**Comment by asiekierka** [comment]
I, myself, would be very disappointed if vanilla redstone lost its dust-esque look.

**Comment by adrwa** [comment]
i agree with asie ^^

**Comment by CyanideX** [comment]
I wouldn't. The dust is stupid and ugly.

**Comment by MechWarrior99** [comment]
I agree with Coded and asie. (just putting my two cents in)

**Comment by ChloeDawn** [comment]
The texture is too noisy when the redstone is powered; it needs a lot less contrast.
I'm not sure what the thought process behind the joiner/dot was; it doesn't look like *anything*, it's just, a box, for no reason. Maybe try to make it look like overlapping wires? Or just shrink it to the same height/width as the straight wires?

**Comment by Prospector** [comment]
I also agree with asie and coded and mech. If it's not gonna be a dust, you should change redstone dust to redstone wire, and then redstone ore would drop a wire...how about you just make it back into a dust.

**Comment by CyanideX** [comment]
It's not that it has to be a wire, it's that the dust looks horrible.

**Comment by Mattabase** [comment]
The only reason I made wires was that Cyanide had started messing with Redstone and it looked like wires and I like wires.

I added the joiner/dot for a couple reasons, I made it because I needed something for a single Redstone, and then later added it to the top because it allowed me to avoid z fighting while creating fewer connection states.  I am sure it could be done without the dot, but with my fairly limited RP knowledge it was the solution I went with. 

As for the noise while it is powered, yes I agree. I messed with it a ton. This is where I landed while being the happiest. I also considered no noise at all but ended feeling to clean.

**Comment by Yulife** [comment]
IMO the idea is great but the texture does not look very Unity. I'd make it less noisy and add shading (idk if that could clash in certain positions)

**Comment by UndarkAido** [comment]
IMO this looks like something from one of those flat texture packs with noise applied. I don't feel it fits into Unity's aesthetic or end goal.

**Pull request closed without merging**
