### PR TITLE
Added chickenchunks and enderchests

### PR DESCRIPTION
**Pull request by exmex**

### CODE REVIEW

**Comment by Yulife** [comment]
Please don't include PSDs in Unity unless it's a heavily multilayered texture. Also please remove any original textures!

**Comment by exmex** [comment]
You could've said that before lol.

**Comment by Yulife** [comment]
Well, I thought it was kind of self-explanatory :)

**Comment by Yulife** [comment]
What about WR-CBE, Translocators and NEI?

**Comment by exmex** [comment]
I don't have translocators installed. But the rest I'm still working on :)

**Comment by Yulife** [comment]
Nice, can't wait :)

**Comment by Yulife** [comment]
If you want me to merge the pull request I will go ahead unless you are still working on translocators @esmex :)

**Comment by Yulife** [comment]
I'ma merge it and if you have some textures planned just make another PR.

**Comment by Yulife** [comment]
Completed some textures. You missed the ender chest corners and the whole ender tank and ender bag textures.

**Pull request merged**
