### PR TITLE
Chisel Support Phase I (wood planks)

### PR DESCRIPTION
**Pull request by ScottKillen**

### CODE REVIEW

**Comment by ScottKillen** [comment]
Oak Planks as a sample:

_Before_


_After_

**Comment by ScottKillen** [comment]
@CyanideX I have fixed the issues with the borders. See above. I couldn't get to sleep until it was done. :grinning:

**Comment by CyanideX** [comment]
*drools*

Will test this first thing tomorrow! :)

**Comment by Yulife** [comment]
Oh my god, finally the ugly dark oak colour of Chisel is gone :thumbsup:

**Pull request merged**
