### PR TITLE
Blood magic update

### PR DESCRIPTION
**Pull request by BBoldt**
Currently in progress.

### CODE REVIEW

**Comment by Yulife** [comment]
Is this done? Hurry up pal so we can push a new build to Curse.

**Comment by BBoldt** [comment]
Before: 


After:


Before: 


After:

**Comment by BBoldt** [comment]
Still not completely up to date, there are a lot of things that still need textures, but it's probably safe to push with the next Unity update.

**Comment by BBoldt** [comment]
fixed this there ^

**Comment by Yulife** [comment]
I'll take a look.

**Comment by CyanideX** [comment]
I'd change that tornado item. Everything else is great.

**Comment by BBoldt** [comment]
Got any ideas of what I should do to replace the tornado? It's "aether", so maybe a cloud or something?

**Comment by CyanideX** [comment]
Cloud sounds good. Or airy dust.

**Comment by Yulife** [comment]
You can find some cloud sprites by me in the Chisel items @BBoldt

**Comment by Yulife** [comment]
Doing a bunch of textures as well to get almost every done. We have a problem though, there's a new Bound Armour model that will be tough to texture.

**Comment by Yulife** [comment]
General:
Before:

After:


Meteor:
Before:

After:


Bazooka:
Before:

After:




GUI:
Before:

After:

**Comment by BBoldt** [comment]
👌👀👌👀👌👀👌👀👌👀 good shit go౦ԁ sHit👌 thats ✔ some good👌👌shit right👌👌there👌👌👌 right✔there ✔✔if i do ƽaү so my self 💯 i say so 💯 thats what im talking about right there right there (chorus: ʳᶦᵍʰᵗ ᵗʰᵉʳᵉ) mMMMMᎷМ💯 👌👌 👌НO0ОଠOOOOOОଠଠOoooᵒᵒᵒᵒᵒᵒᵒᵒᵒ👌 👌👌 👌 💯 👌 👀 👀 👀 👌👌Good shit

**Comment by Yulife** [comment]
Don't smoke pot while working @BBoldt

**Pull request merged**
