### PR TITLE
Blood Arsenal and Arcane Arteries [READY TO MERGE]

### PR DESCRIPTION
**Pull request by Kalut**
This is hopefully the final iteration and is ready for merger. :relieved: :satisfied:

Blood Arsenal:
Before:
final preview before
After:
final preview after

Items:
blood arsenal items tweaked 4

the shards are animated:
Shard Animated

Arcane Arteries 
Before:
Default
After:
Retexture

To do:
- ~~change diamonds~~
-  change diamond storage block
- ~~redo shard textures~~
- ~~cake (fix cake derp)~~
- ~~slate block tweaks~~
- ~~add detail to armor~~
- ~~textures for bauble stuff~~
- ~~tweak book texture~~

~~Initial Commit, still needs feedback,~~

~~I'm not happy with how the money and to a lesser extent the diamonds turned out, would like some feedback on how to improve those.~~

New Diamond textures have been added,

### CODE REVIEW

**Comment by Yulife** [comment]
I think the money is fine. You're right on the diamonds. Maybe take a look at other crystals and Unity and try to improve it from there?

**Comment by CyanideX** [comment]
Could I see some screens?

**Comment by Kalut** [comment]
Put some new screenshots in the OP, as well as the old stuff.

As far as the Diamonds go, I'm not sure how to do those, I didn't want to deviate from the minecraft shape, I did include a texture as an alt that was more in line with the shards from BM but it looked a bit busy for my tastes. Might have a look at it again, but I'm still not sure how to differentiate the 3 first tiers  of diamonds.

**Comment by Yulife** [comment]
Look at @CyanideX 's nether diamond from Infernal Skies perhaps :3

**Comment by Yulife** [comment]
OR be really fancy and use unity's bound blade style :)

**Comment by Kalut** [comment]
I took a look at @CyanideX 's nether diamonds and those are amazing, would love to base the blood diamonds on those if that's ok?

**Comment by Yulife** [comment]
Also, the altar sort of thing - make the red part in the hanging-down-carpet more thick.

**Comment by Kalut** [comment]
ItSs a Bound Diamond Block, I will have a look at it once I have redone the diamonds.

**Comment by Yulife** [comment]
You could take a look at other crystal block textures of Unity and make the highlights really yellow instead of having a really light border. Not sure how that turns out, worth a try. Excuse my non-knowledge about the mods but on the bottom row, the second "rune" yellow block in default, why does it look so plain in Unity? The gem cluster could use some more sparkling in each of the gems :) The cake needs a rework as well. Maybe make it like a layered Red Velvet? Also, what's the orange fluid in the bottle? You could take a peek at my dragon's breath texture and rework it from there! :stuck_out_tongue_winking_eye: Not sure about the bottom row with baubles with thaumcraft integration :laughing:

**Comment by Kalut** [comment]
Those "Runes" are just slate blocks as far as i can tell not sure what they are used for, as the t2 slate in unity is more plain I did the same with the block
Imgur
The orange fluid is just orange juice, so i really didn't see a reason to touch it. I agree with the cake i just hadn't had the time to come up with anything also, I only did the first 2 necklaces from the last row, is there anything in particular you don't like about those?

**Comment by Yulife** [comment]
Well the ring needs some shading and noise as well as the necklaces :)

**Comment by CyanideX** [comment]
I think everything looks phenomenal! The items really have a theme that is consistent with tools and weapons. The armor could have a little more depth but I like the helmet a lot.

I think those crystals with the sparkles around them could be done differently; I've never been a fan of stray pixels and always preferred integrating variation into the main design.

Also, I think the slates storage block should have more texture to it. Perhaps layers like they're stacked like this: 
slates

Please don't use that one, it's a horrible, ugly example. :stuck_out_tongue: 

Other than that, I think you've done a great job. :grinning:

**Comment by Yulife** [comment]
Doesnt the block texture use one texture for all sides? Wouldnt it look weird if there's a stacking texture ontop or below? :p

**Comment by CyanideX** [comment]
Yes, but I like the look of the graphite storage blocks. Especially when used
for decoration. Your call though.

On Fri, Nov 06, 2015 at 2:51 PM, Yulife < notifications@github.com [notifications@github.com] > wrote:
Doesnt the block texture use one texture for all sides? Wouldnt it look weird if
there's a stacking texture ontop or below? :p

—
Reply to this email directly or view it on GitHub
[https://github.com/CyanideX/Unity/pull/50#issuecomment-154567980] .[https://github.com/notifications/beacon/AC9njLU_luH0SwSoD7mVgRj13ynVIOYCks5pDSaAgaJpZM4GccJM.gif]

**Comment by Yulife** [comment]
Right, forgot that. Good point :stuck_out_tongue:

**Comment by Kalut** [comment]
I did try something similar to what you posted a bit more subtle though, I'm also toying with the idea of chains inspired by Diablo 3: 
slate chains

**Comment by Kalut** [comment]
Did the Guide book, and decided to also do the wolf hide.
image
image

**Comment by Yulife** [comment]
Looked at the new changes, much better! Love the wand & baubles :smile:

**Comment by Kalut** [comment]
Thanks!

Added the last stuff, unless there are any problems this is finished and ready for merger.

**Comment by Kalut** [comment]
Thanks! :blush:

Did some cleanup, and a some fixes, It should now be essentially finished. I also added some pictures in the OP, with all of the new textures for review.

**Comment by Yulife** [comment]
The way you modified the Blood TNT side texture, did you also do it to the top one? It may just be the angle but it looks off. The money, I actually liked the old better. May need @CyanideX and @BBoldt opinion too. What's up with [these](http://i.imgur.com/zuyASkQ.png) textures by the way? Instead of just lowering the saturation at the border of the Blood Lamp, take a look at the Prismarine Lamp in Unity and replace the edge with something that would fit :)

**Comment by Kalut** [comment]
Yea, I modified the TNT textures, I reverted it to match the Unity top/bottom. I added a new Blood Lamp and as for those things, I must have missed them,[here](https://cloud.githubusercontent.com/assets/15369008/11165657/0992876c-8b0d-11e5-845c-d9a11ead1198.png) are the textures I meant to add.

**Comment by Yulife** [comment]
I'm slightly confused... does the TNT look unique from the vanilla unity one now or does it look the same?

**Comment by Kalut** [comment]
Eh, the side texture is still unique (the one that says TNT), but the top is now using the default unity texture.

**Comment by Yulife** [comment]
Please make it uniform looking, otherwise it's going to look off. So side, bottom and top need to be the same style.

**Comment by Kalut** [comment]
like this?blood_tnt_bottom I thought you said you they where off.

**Comment by Yulife** [comment]
Yeah that's great

**Comment by TehNut** [comment]
>Guide Book

Could I actually steal that and modify it slightly for the default GuideAPI texture?

**Comment by CyanideX** [comment]
You could use any of the Unity books if you wish to.

**Comment by BBoldt** [comment]
@Kalut, you want to add your Sanguimancy stuff in with this pull request as well? Might as well continue the conversation with that since it's very related.

Everything looks great to me btw, you've done a great job!

**Comment by Kalut** [comment]
@BBoldt, the Sanguimancy textures are still very much WIP and will probably take a while to get done, so I would prefer not to include them now. But if you want to wait than that's up to you.

**Comment by Yulife** [comment]
If they will take too much time just make another PR :) Great work, much appreciated!

**Comment by Arcaratus** [comment]
Wow, never noticed this but as the texturer of all those crappy textures, I love the ones that are presented! I might even use them...

**Comment by TehNut** [comment]
@Arcaratus I totally didn't link you this like a month ago

**Comment by CyanideX** [comment]
@Arcaratus, any and all textures are free to use; however, because it is an addon, I would suggest sticking with the vanilla textures as to fit in well with the base mod.

**Comment by TehNut** [comment]
I tried convincing him of that. He said no.

**Comment by BBoldt** [comment]
how times have changed

**Comment by CyanideX** [comment]
@TehNut, fixed that for you. :stuck_out_tongue:

**Comment by Yulife** [comment]
Hey @Kalut you still avaible? @Arcaratus may need some textures for Blood Arsenal in your style

**Comment by Arcaratus** [comment]
Yep! I do indeed.

**Comment by Kalut** [comment]
Sure! I could give it a shot.

**Pull request merged**
