### PR TITLE
Chisel Hardened Clay to match Unity's

### PR DESCRIPTION
**Pull request by oitsjustjose**
Fixes the tone being off - Chisel's was very orange to match Vanilla textures. Lowered saturation and lightness on all hardened clay textures.

Oh yeah, this is for 1.10.2 if that matters ;)

### CODE REVIEW

**Comment by Yulife** [comment]
Could you make like a before after pic? :)

**Comment by oitsjustjose** [comment]
**Before:**




**After:**




(Sorry for MC time difference, this was in my survival world)

**Comment by oitsjustjose** [comment]
Also just tossed in some Quark Bed textures!

**Before:**




**After:**

**Comment by Yulife** [comment]
I like the beds. Did you use the unity base for the hardened clay?

**Comment by oitsjustjose** [comment]
I used my own judgement along with the stock chisel textures. They're just
a recolor to match. Drullkus' texture work is already very good.

**Comment by Yulife** [comment]
I'll merge but the Hardened Clay texture may change soon due to tiling issues but thanks a lot for the textures, I'll make sure to give you credit :D

**Pull request merged**
