### PR TITLE
Router Reborn retexture

### PR DESCRIPTION
**Pull request by BBoldt**
Attempt 2.
#12 <--- Old PR.

Before:

After:

### CODE REVIEW

**Comment by CyanideX** [comment]
Beautiful.

**Comment by BBoldt** [comment]
:smile: 

I've finally officially contributed to Unity!

**Comment by Yulife** [comment]
I love the little sparkle :3

**Comment by UnixRonin** [comment]
I really like this look, but I'd love to see a 64x version.
How feasible would it be, do you suppose, to use a .mcmeta to add animated blinkenlights?  :)

**Comment by CyanideX** [comment]
Unity isn't 64x; you would need to create your own iteration at that resolution. Animated lights are easy enough to make, perhaps @BBoldt would be up to working those into the next version. :smile:

**Comment by BBoldt** [comment]
I'm not really sure where I would add the blinky lights.

**Comment by CyanideX** [comment]
To the colored part of the texture. The screen.

**Comment by Yulife** [comment]
@CyanideX what's your trick to get the "off" colour of an "on" colour? Do you just decrease the brightness or what...?

**Comment by CyanideX** [comment]
@Yulife, I always use levels and saturation controls. Lowing the max output levels until the screen is dark and then boost the saturation slightly. When the lights are active I typically add an outer glow of the darkest color in the screen, and then increase the white levels.

**Comment by BBoldt** [comment]
Removed from Unity, if anyone comes across this post and wants these textures, they are here:

http://opengameart.org/content/router-textures

**Comment by Yulife** [comment]
Por que

**Pull request merged**
