### PR TITLE
PressurePipes Unity

### PR DESCRIPTION
**Pull request by VapourDrive**
This is a unity themed retexture of the pressure pipes mod by Bdew
The previous textures were all 32x and heavily interpolated from scaling.
The new textures are fairly high contrast with some rough noise in plainer textured areas and shading gradients where there are presumed edges, if there are any specific textures that stand out I am open to redo them or change them. The items and blocks follow a uniform style, design and colour pallete. Bright colours are slightly saturated and darkened so as not to stand out.
These are my new textures:

These are the old textures:

### CODE REVIEW

**Comment by CyanideX** [comment]
I think they're certainly better than the originals but I do think they're missing something. They need a bit more definition and less random noise. Perhaps adding rivets to the piping or subtle shading around the details may give it a more complete look.

Also, by looking at the two blocks on the right end, I can't actually tell what they are. At first glance the one thing that stood out to me were the dark details on the light background; I would suggest matching the other tones.

I hope this came off as constructive and not insulting; your textures aren't bad, they simply need tweaking. :)

**Comment by VapourDrive** [comment]
It definitely is constructive. One of the reasons why I want to help with this project is to truly force myself to produce work that meets a standard. Force myself to improve, etc.

**Comment by CyanideX** [comment]
That's a great mindset! Feel free to continue working on these and resubmit. I would like to see your progress. :)

**Comment by VapourDrive** [comment]
A new comparrison of the reworkded textures:
My tank textures: the controller is based off of the screen from the psd; a slightly different colour for the sake of fitting the blue-ish overal theme of the textures. The tank now has a ribbed texture instead of a completely plain look.

The original tank textures.


My pipe and infinite water source block textures, the pipe colour is meant to look less plain now, and is a softer blue. The pipe is also difficult as all the pipe's textures are pulled from different parts of one 16x png. The source block is based off of the iron block with a tinted rim, the water is behind glass instead of a completely blue block.

The original pipe and infinite water source block textures.


My drain, pump, inlet and outlet textures. Lighter blue overall, the controller glass is used wherever a fluid overlay may be placed. Based off of the iron blocks with a tone contrast in a similar style to unity MFR machines.

Original drain, pump, inlet and outlet textures.


My item textures, the controller is now a proper looking wrench. The fluid interface is used in block recipes where a pipe would connect to a block, so I made it look like a gasket. The canister is similar, just not 64x and more textured than the plain old one. The system interface is no longer a random enderpearl plate but a handlheld device. The tank wall item is bassed off of the tank blocks.

Original items.

**Comment by VapourDrive** [comment]
Changed interface item icons

**Comment by CyanideX** [comment]
These are much better! They have more detail, consistent colors, and the texture variation adds much needed depth. Overall, they're starting to look like they would fit well with Unity.

My suggestions: Some of the pipes and other blocks could use some shading (try dithering with darker colors). I also think the water source block could use some depth on the inside; inner shadows around the water. Finally, the only other thing I have to say is that the tank, while much better than the first iteration, still doesn't quite work for me. The lines are a nice addition but they don't tell me what they're there for. If you added rivets along them with subtle shading below, I would think they were bars holding the tank together. ;) Perhaps a more familiar iron block texture with less contrasting bands would be another solution. Also, instead of having the grey stripe textures wrap around the block face elements, try having them go under them.

Sorry for the long critique. You're improving quite quickly so I don't think there will be many more of these. :)

**Comment by VapourDrive** [comment]
Hopefully the final update to the pull request

Tank Blocks:
New:

Old:


Other Blocks: water source, high pressure pump, drain, high pressure IO, pipe
New:

Old:


Items: high pressure interface, tank wall, fluid interface, hand pump, canister, configurator
New:

Old:

**Comment by CyanideX** [comment]
VapourDrive... near perfect! That tank looks fantastic! :D

The only thing that caught my eye this time were the pipes. I'm not a fan of the blue in particular and I think the border needs to be one pixel thicker. They also lack definition compared to the tanks which you so wonderfully perfected. :kissing: Try adding some details to those; perhaps a few rivets, sheet metal or scratches (unless the textures just get stretched... in that case just make the texture more metallic in color with less variations). Do that and this retexture is officially in Unity. :)

**Comment by VapourDrive** [comment]
Removed the blue tint from the tank pressure IO blocks.

Made the pressure and drain blocks all more similar to the mfr machine blocks, the idea being that the pressure section looks reinforced. The infinite water source and pump are now just iron coloured and the water look has more depth.

**Pull request merged**
