### PR TITLE
Extreme Reactors

### PR DESCRIPTION
**Pull request by karlramberg**
I took the time to reuse the Unity textures for Big Reactors in Extreme Reactors, since Extreme Reactors is a 1.10.2 port of Big Reactors. I also added a few new textures (ie. Wrench or Steel). The reactor and turbine controllers were also changed.

### CODE REVIEW

**Comment by MechWarrior99** [comment]
Cool! Could you show screenshots of all new/edited textures?

**Comment by Quillan27** [comment]
Yeah, here they are. Everything else is taken from 1.7.10.
http://imgur.com/a/WupMH

**Comment by MechWarrior99** [comment]
The center green/blue part on the controller is a screen. So it doesn't make much sense to have dark shadowing around the boarder.
I would take a ingot from unity and recolor it to fit the steal coloring.
I like the dust.
I would maybe take down the saturation on the wrench handle, and add a bit more contrast to the metal head part.  

Thanks for doing this!

**Comment by Quillan27** [comment]
A screenshot for the changes.
http://imgur.com/a/yajDF

**Comment by InsomniaKitten** [comment]
Why did you change the controller textures? That wrench doesn't fit into Unity at all.. Try making it shorter and thicker?

**Comment by Quillan27** [comment]
I changed the controller because I thought the 1.7.10 textures were too busy. The screen had a weird gradient from the top left to the bottom right. The layout of the texture didn't change, I only simplified the screen and made the button red.

About the wrench... Are there any clear guidelines for making Unity textures that I should look at?

**Comment by CyanideX** [comment]
@Quillan27 I'm sorry nobody got back to you sooner. There aren't any clear guidelines for Unity, although I've been wanting to do some, but the best point of reference would be the latest committed textures. Look through existing ones and use them as a base, making changes as needed.

**Comment by karlramberg** [comment]
Why was this closed? I'm still working on it, I've just been very busy.

**Comment by ChloeDawn** [comment]
Accidental. Cy was refactoring branches and the master branch was deleted in the process.

**Comment by adrwa** [comment]
cy fucked up from what i've seen

**Comment by ChloeDawn** [comment]
~~@Quillan27 Open a new pull request to the 1.11 branch; nothing will be lost except for the comments on this current one. Pull requests can't be deleted so you can still use it for reference.~~

**Pull request closed without merging**
