### PR TITLE
Thermal Foundation textures

### PR DESCRIPTION
**Pull request by VapourDrive**
Storage block textures given by CyanideX, missing ones added myself along style.
Gears based off of old thermal expansion textures, re-coloured to represent the new metal scheme
Ingots, ores and nuggets recoloured to represent new metal scheme.

Listed items are given in itemfram order of "natural page reading"

Old storage and ore blocks
Bronze, signalum, lumium, electrum, copper, tin, silver, lead, nickel, platinum (shiny), mithril (mana)

New storage and ore blocks

Old ingots
Copper, tin, silver, lead, nickel, platinum (shiny), mithril (mana), electrum, invar, bronze, signalum, lumium, electrum

New ingots

Old dusts
Coal, charcoal, obsidian, sulphur (non-regular dust), niter (non-regular dust), electrum, invar,
cinnabar, iron, gold, copper, tin, bronze, signalum, silver, lead, nickel, platinum (shiny), mithril (mana),
lumium, enderium

New dusts

Old nuggets
iron, copper, tin, silver, lead, nickel, platinum, mithril (mana), electrum, invar, bronze,
signalum, lumium, enderium

New nuggets

Old gears
iron, gold, copper, tin, silver, lead, nickel, platinum (shiny), mithril (mana), electrum, invar, bronze,
signalum, lumium, electrum

New gears

*Notes
I made some minor changes to some of the sent items and blocks, nickel is slightly less green (very slightly)
Enderium is slightly more blue than the version you sent to me, the slightly more blue one matches the enderpearls more.

### CODE REVIEW

**Comment by VapourDrive** [comment]
Old storage blocks with invar, I forgot in teh upper screenshots.

New storage blocks


Changed sulphur and niter, more like mini dusts (without dropping in size too much)


Made the enderium ingot have a smoother batch of purple splotches.

**Comment by VapourDrive** [comment]
Rivets on the lumium storage block, enderium has more natural looking blue-ish corner.

**Comment by VapourDrive** [comment]
New cinnabar texture.
crystalcinnabar

**Comment by CyanideX** [comment]
cinnabar
cinnabar2
cinnabar3
cinnabar4
cinnabar5

**Comment by VapourDrive** [comment]
Old Cinnabar

New Cinnabar

**Pull request merged**
