### PR TITLE
ProgressiveAutomation

### PR DESCRIPTION
**Pull request by Quillan27**
This fixes Progressive Automation textures for 1.9+. The current file structure did not work with newer versions. I added a few textures that were missing but most  only got moved around and renamed.

http://imgur.com/a/BxEcS

### CODE REVIEW

**Comment by BBoldt** [comment]
We need to set up different branches on here for the different versions of Minecraft, otherwise the github is only going to work for the latest version, and I don't think that's a good idea.

**Comment by CyanideX** [comment]
Good call, @BBoldt. Care to set those up for us? :wink:

**Comment by Quillan27** [comment]
So what version of Minecraft is Unity officially supporting right now?

**Comment by Yulife** [comment]
1.7.10/1.8/1.9/1.10.2

**Comment by Yulife** [comment]
Thanks for the fix! We'll make sure to give you credit in the changelog

**Pull request merged**
