### PR TITLE
Hardcore Ender Expansion & Biomes o' Plenty

### PR DESCRIPTION
**Pull request by Yulife**

### CODE REVIEW

**Comment by Yulife** [comment]
Before:


After:

**Comment by BBoldt** [comment]
sweet

**Comment by Yulife** [comment]
Before:

After:

**Comment by Yulife** [comment]
@CyanideX this ready to merge?

**Comment by CyanideX** [comment]
Why does the red fluid now look like it's still and not flowing?

**Comment by Yulife** [comment]
It's Crag which is more of a tealish color. I'll take a look.

**Comment by Yulife** [comment]
Okay, the fluid is normal looking in my world. Merging!

**Pull request merged**
