### PR TITLE
Update Advanced Machines

### PR DESCRIPTION
**Pull request by InsomniaKitten**
Update the existing Unity textures to work with [Chocohead's 1.10.2 version](https://minecraft.curseforge.com/projects/advanced-machines) of the mod.

### CODE REVIEW

**Comment by Yulife** [comment]
Did you modify the JSONs?

**Comment by InsomniaKitten** [comment]
Yes, I unified some of the textures as they had individual identical textures for some machines faces. I cut it down to one texture per and modified the JSONs accordingly.

**Comment by Yulife** [comment]
Ah that makes sense! Thanks for the submission

**Comment by InsomniaKitten** [comment]
I missed a bit >.< https://github.com/CyanideX/Unity/pull/86

**Pull request merged**
