### PR TITLE
Connected Textures

### PR DESCRIPTION
**Pull request by VinnyStalck**
Connected Textures for Smooth Andesite, Diorite and Granite.
Overlays for Dirt, Grass, Gravel, Sand and Oak Leaves.

image

### CODE REVIEW

**Comment by CyanideX** [comment]
Do you have any additional screenshots showing all of the other changes? 🙂

**Comment by VinnyStalck** [comment]
> Do you have any additional screenshots showing all of the other changes? 🙂

### Nature
image
image
image
image


### Dirt, Sand and Gravel overlay in action underwater
image

### Dirt overlay in caves
image

### Oak Leaves overlay
image
image

### Connected Polished Stones
image

**Review by ChloeDawn — CHANGES_REQUESTED** [review]
Noticeable tiling issues on the connected textures for polished stones

**Comment by VinnyStalck** [comment]
> Noticeable tiling issues on the connected textures for polished stones

Fixed

image


https://github.com/StalckGx/Unity/commit/cf14b3d1f0cb16838edacc1e7fa4eb4b66b72d52

**Comment by CyanideX** [comment]
I still see some odd seams on the connected textures. 

image

Why not use the base texture instead of altering the polished version?

**Comment by VinnyStalck** [comment]
> Why not use the base texture instead of altering the polished version?

Yeah... I had not thought of doing this.
I hope it looks better now.

image
https://github.com/StalckGx/Unity/commit/c40af955a91dc3a069fa71b932a94e6084adb422

**Comment by CyanideX** [comment]
I have changed the textures for those stone types but I would love to see another PR added once OptiFine updates to 1.15 since that is the version I plan to focus on at the moment. I have created a separate repo for the OptiFine addon: https://github.com/CyanideX/Unity-Extras

**Pull request closed without merging**
